In [1]:
import pandas as pd

In [ ]:
Creating DataFrames

In [2]:
data = {'Name':['Alice','Bob'],'age':[25,30]}

In [3]:
df = pd.DataFrame(data)

In [4]:
lst=[['Alice',25],['Bob',30]]

In [5]:
df = pd.DataFrame(lst, columns=['Name','Age'])

In [6]:
df.head()

    Name  Age
0  Alice   25
1    Bob   30

In [7]:
df.tail()

    Name  Age
0  Alice   25
1    Bob   30

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      str
 1   Age     2 non-null      int64
dtypes: int64(1), str(1)
memory usage: 164.0 bytes

In [9]:
df.describe()

             Age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [ ]:
Selecting Data

In [10]:
df['Name']

0    Alice
1      Bob
Name: Name, dtype: str

In [11]:
df[['Name','Age']]

    Name  Age
0  Alice   25
1    Bob   30

In [12]:
df.loc[0]

Name    Alice
Age        25
Name: 0, dtype: object

In [13]:
df.iloc[1]

Name    Bob
Age      30
Name: 1, dtype: object

In [14]:
df[df['Age']>25]

  Name  Age
1  Bob   30

In [ ]:
Adding/Removing columns

In [15]:
df['Gender']=['F','M']

In [16]:
df.drop('Age',axis=1,inplace=True)

In [ ]:
Handling Missing Data

In [17]:
df.isnull()

    Name  Gender
0  False   False
1  False   False

In [18]:
df.dropna()

    Name Gender
0  Alice      F
1    Bob      M

In [19]:
df.fillna(0)

    Name Gender
0  Alice      F
1    Bob      M

In [ ]:
grouping and Aggregating

In [20]:
df['Age']=[26,46]

In [21]:
df.groupby('Gender')['Age'].mean()

Gender
F    26.0
M    46.0
Name: Age, dtype: float64

In [ ]:
Merging and joining

In [22]:
import pandas as pd

df1 = pd.DataFrame({
    'key': [1, 2, 3],
    'Name': ['A', 'B', 'C']
})

df2 = pd.DataFrame({
    'key': [1, 2, 4],
    'Marks': [90, 85, 95]
})

In [23]:
pd.merge(df1, df2, on='key')

   key Name  Marks
0    1    A     90
1    2    B     85

In [24]:
df1.set_index('key').join(df2.set_index('key'))

    Name  Marks
key
1      A   90.0
2      B   85.0
3      C    NaN

In [ ]:
Reading/Writing Files

In [25]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['A', 'B', 'C'],
    'Age': [20, 21, 22]
})

df.to_csv('data.csv', index=False)

In [26]:
pd.read_csv('data.csv')

  Name  Age
0    A   20
1    B   21
2    C   22

In [27]:
df.to_csv('output.csv', index=False)

In [ ]:
Useful Functions

In [28]:
df.sort_values('Age')

  Name  Age
0    A   20
1    B   21
2    C   22

In [29]:
df['Age'].apply(lambda x:x+1)

0    21
1    22
2    23
Name: Age, dtype: int64

In [30]:
df['Name'].unique()

<StringArray>
['A', 'B', 'C']
Length: 3, dtype: str

In [31]:
df['Age'].value_counts()

Age
20    1
21    1
22    1
Name: count, dtype: int64